# Generated by Django 4.2.6 on 2023-10-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstoreapp', '0004_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('timg', models.ImageField(upload_to='pics2')),
                ('tdesc', models.TextField()),
            ],
        ),
    ]
